# Generated by Django 4.2.5 on 2023-10-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='age',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='budget',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='degree',
            field=models.CharField(default='nada', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='dni',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='modality',
            field=models.CharField(default='nada', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='specialty',
            field=models.CharField(default='nada', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoextra',
            name='user_type',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
