# Generated by Django 4.2.5 on 2023-10-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyUsers', '0002_infoextra_age_infoextra_budget_infoextra_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='age',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='budget',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='degree',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='modality',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='infoextra',
            name='specialty',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
