# Generated by Django 4.2.5 on 2023-10-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('budget', models.CharField(max_length=40)),
                ('motive', models.CharField(max_length=1500)),
                ('score', models.CharField(max_length=40)),
                ('id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('cuil', models.IntegerField(max_length=11)),
                ('is_banned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('specialty', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=40)),
                ('modality', models.CharField(max_length=40)),
                ('fee', models.IntegerField(max_length=40)),
                ('score', models.IntegerField(max_length=40)),
                ('id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('cuil', models.IntegerField(max_length=11)),
                ('is_banned', models.BooleanField()),
            ],
        ),
    ]
