# Generated by Django 4.2.5 on 2023-10-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyApp', '0002_alter_patient_cuil_alter_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='score',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
