# Generated by Django 4.2.5 on 2023-10-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyApp', '0003_remove_profesional_cuil_remove_profesional_is_banned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('modality_required', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('request_description', models.TextField()),
                ('budget', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
