# Generated by Django 4.2.5 on 2023-10-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyApp', '0004_therapyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyrequest',
            name='modality_required',
            field=models.CharField(choices=[('opcion1', 'Cualquier modalidad'), ('opcion2', 'Terapia Cognitivo-Conductual'), ('opcion3', 'Terapia Psicodinámica'), ('opcion4', 'Terapia Humanista'), ('opcion5', 'Terapia Gestalt'), ('opcion6', 'Terapia de Pareja'), ('opcion8', 'Terapia Familiar'), ('opcion9', 'Terapia de Grupo'), ('opcion10', 'Terapia de Apoyo')], max_length=40),
        ),
    ]
