# Generated by Django 4.2.5 on 2023-10-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TherapyApp', '0005_alter_therapyrequest_modality_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
    ]
